#use latest python runtine base image
FROM python:3.6.3-alpine3.6

#set working dir and copy to image
WORKDIR /app 
COPY . /app

#run helloworld.py when container launces
CMD ["python", "hellovikas.py"]
