import os
import json
from time import time
from datetime import datetime, timedelta

# Apache Airflow
from airflow import DAG
from airflow.operators.dummy_operator import DummyOperator
from airflow.operators.python_operator import PythonOperator

# from airflow.decorators import dag, task
# Newspaper3k
import newspaper
from newspaper import Article

#
# Quilt
# import t4
# from newspaper import Article

default_args = {
    'owner': 'Vikas',
    'depends_on_past': False,
    'start_date': datetime(2022, 1, 1),
    'email': ['vikas.kumbharkar@gmail.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    'provide_context':True
}

# DAG
dag = DAG(
    'scrap_news_data',
    default_args=default_args,
    schedule_interval=timedelta(days=1))

# Operators
def scrape_articles(**kwargs):
    """
    Scrape articles from one or more online newspaper sources
    Parameters
    ----------
    kwargs : dict
        Dictionary that contains all keyword arguments & values
    Returns
    -------
    sources_keywords : dict
        List of all keywords generated per source
    """
    sources = kwargs['source_urls']
    category = kwargs['category']

    sources_keywords = dict()

    print(f"Scrape headlines from {len(sources)} sources that include '{category}' in the url")
    for s in sources:
        print(f"START: Scrape articles from '{s}'")
        print(f"START: Build newspaper")
        paper = newspaper.build(s,memoize_articles=False)
        print(f"END: Build newspaper")
        keywords_list = list()
        print("START: Collect articles")
        for article in paper.articles:
            if category in article.url:
                print(article.url)
                single_article = Article(article.url)
                single_article.download()
                count = 0
                while single_article.download_state != 2:
                    # ArticleDownloadState.SUCCESS is 2
                    count = count+1
                    time.sleep(count)
                single_article.parse()
                single_article.nlp()
                keywords_list.extend(single_article.keywords)
        if len(keywords_list) == 0:
            keywords_list.append("Error: No keywords")
        sources_keywords[s] = keywords_list
        print("END: Collect articles")
        print(f"END: Scrape articles from '{paper}'")
    print('Keywords and sources keywords',keywords_list,sources_keywords)

    return sources_keywords

def write_to_json(**context):
    """
    Write keywords generated by NLP to local JSON file
    Parameters
    ----------
    context : dict
        Context object that contains kwargs and Xcom data
    Returns
    -------
    status : boolean
        Status of writing sentiment to disk
    """
    data_directory = context['directory']
    file_name = context['filename']
    print('\nTask Instance:',context['task_instance'])
    keywords = context['task_instance'].xcom_pull(task_ids='scrape_articles')
    print("Keywords Extracted finally",keywords)
    keywords_dict=json.loads(keywords)
    print('Keywords Extracted_dictionary',keywords_dict)
    file_names = list()
    for k in keywords:
        # Strip leading 'https://' and trailing '.com'
        domain = k.replace("https://","")
        domain = domain.replace(".com", "")
        new_fname = f"{data_directory}/{domain}_{file_name}"
        file_names.append(new_fname)
        with open(new_fname, 'w') as f:
            json.dump(
                keywords[k],
                f,
                ensure_ascii=False,
                indent=2,
                sort_keys=True
            )
    return file_names

# Tasks
task1 = PythonOperator(
    task_id='headlines_extraction',
    python_callable=scrape_articles,
    op_kwargs={
        'source_urls': [
            # 'https://theguardian.com',
            'https://nytimes.com',
            'https://cnn.com'
        ],
        'category': 'food'
    },
    do_xcom_push=True,
    provide_context=True,
    dag=dag
)

task2 = PythonOperator(
    task_id='write_to_json',
    python_callable=write_to_json,
    op_kwargs={
        'directory': 'data',
        'filename': 'keywords.json'
    },
    provide_context=True,
    dag=dag

)


# Set dependencies
task1 >> task2